const mongoose = require('mongoose');

const PhotoSchema = new mongoose.Schema({
  // Ownership
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // File Paths
  imageUrl: {
    type: String,
    required: [true, 'Original image path is required']
  },
  thumbnailUrl: {
    type: String                            // Generated by 'Sharp' on the backend for performance
  },

  // Metadata from AI (Updated via PUT request after browser analysis)
  qualityScore: {
    type: Number,
    default: 0                              // Calculated by OpenCV.js (Laplacian Variance / Blur Detection)
  },
  faceCount: {
    type: Number,
    default: 0                             // Detected by TensorFlow.js (SSD MobileNet or custom CNN)
  },
  sceneCategory: {
    type: String,
    enum: ['indoor', 'outdoor', 'event', 'unclassified'],
    default: 'unclassified'
  },

  // Status for Trash/Review Module
  isFlagged: {
    type: Boolean,
    default: false                          // True if qualityScore is below user threshold
  },

  // Custom Organization
  tags: {
    type: [String],
    default: []
  },
  
  format: String, // jpeg, png, etc.
  size: Number,   // in bytes
  
}, {
  timestamps: true
});

// Create an Index for fast searching by AI tags
PhotoSchema.index({ user: 1, sceneCategory: 1, qualityScore: -1 });

// Create an Index for Gallery sorting
PhotoSchema.index({ user: 1, createdAt: -1 });

module.exports = mongoose.model('Photo', PhotoSchema);