const mongoose = require('mongoose');

const AlbumSchema = new mongoose.Schema({
  // Ownership
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  title: {
    type: String,
    required: [true, 'Please add an album title'],
    trim: true
  },
  description: {
    type: String,
    maxlength: 200
  },

  // Album Type
  isAutoGenerated: {
    type: Boolean,
    default: false                           // True if the system created it based on AI tags
  }, 
  
  // The Photos
  photos: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Photo'
  }],

  // Cover Image 
  coverPhoto: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Photo'
  },


  categoryTag: {
    type: String,                            // e.g., 'indoor', 'outdoor', 'event'
    default: null
  }

}, {
  timestamps: true
});

AlbumSchema.index({ user: 1, title: 1 }, { unique: true });

module.exports = mongoose.model('Album', AlbumSchema);