const mongoose = require('mongoose');

const AlbumSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  title: {
    type: String,
    required: [true, 'Please add an album title'],
    trim: true
  },
  description: {
    type: String,
    maxlength: 200
  },
  type: {
    type: String,
    enum: ['private', 'shared', 'team'],
    default: 'private'
  },
  tier: {
    type: String,
    enum: ['Root', 'Tier 1', 'Tier 2'],
    default: 'Root'
  },
  category: {
    type: String,
    enum: ['solo', 'group', 'couple', 'general'],
    default: 'general'
  },
  parentFolderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Album',
    default: null
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  isFavorite: {
    type: Boolean,
    default: false
  },
  photos: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Photo'
  }],
  coverPhoto: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Photo'
  },
  categoryTag: {
    type: String,
    default: null
  }
}, {
  timestamps: true
});

AlbumSchema.index({ user: 1, title: 1 }, { unique: true });

module.exports = mongoose.model('Album', AlbumSchema);